# Generated by Django 3.1.4 on 2021-01-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_kolej_management_app', '0002_applyexception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyexception',
            name='admin',
        ),
    ]
