# Generated by Django 3.1.4 on 2021-01-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_kolej_management_app', '0003_remove_applyexception_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyexception',
            name='apply_date',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
