# Generated by Django 3.1.4 on 2021-01-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_kolej_management_app', '0004_applyexception_apply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
    ]
