# Generated by Django 3.1.4 on 2021-02-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_kolej_management_app', '0005_auto_20210118_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyexception',
            name='apply_date',
        ),
    ]
